<?php
/** The ACF Fields */

if ( function_exists( 'acf_add_local_field_group' ) ) :
	/** Page: Festival Info (FAQs + Giveaways) */
	acf_add_local_field_group(
		array(
			'key'                                   => 'group_64526b8ab4c5a',
			'title'                                 => 'Page Fields — Festival Information',
			'fields'                                => array(
				array(
					'key'               => 'field_64526b8bcd038',
					'label'             => 'FAQs',
					'name'              => 'faqs',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 0,
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_64526bb079b73',
							'label'             => 'Banner',
							'name'              => 'banner',
							'aria-label'        => '',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'return_format'     => 'array',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
							'preview_size'      => 'medium',
						),
						array(
							'key'               => 'field_64526bc579b74',
							'label'             => 'Headline',
							'name'              => 'headline',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_64526bd779b75',
							'label'             => 'Subheadline',
							'name'              => 'subheadline',
							'aria-label'        => '',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'default_value'     => '',
							'maxlength'         => '',
							'rows'              => '',
							'placeholder'       => '',
							'new_lines'         => '',
						),
						array(
							'key'               => 'field_64526be579b76',
							'label'             => 'FAQs',
							'name'              => 'faq',
							'aria-label'        => '',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'layout'            => 'table',
							'pagination'        => 0,
							'min'               => 0,
							'max'               => 0,
							'collapsed'         => '',
							'button_label'      => 'Add FAQ',
							'rows_per_page'     => 20,
							'sub_fields'        => array(
								array(
									'key'               => 'field_64526bee79b77',
									'label'             => 'Question',
									'name'              => 'question',
									'aria-label'        => '',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'show_in_graphql'   => 0,
									'default_value'     => '',
									'maxlength'         => '',
									'placeholder'       => 'Question',
									'prepend'           => '',
									'append'            => '',
									'parent_repeater'   => 'field_64526be579b76',
								),
								array(
									'key'               => 'field_64526bfc79b78',
									'label'             => 'Answer',
									'name'              => 'answer',
									'aria-label'        => '',
									'type'              => 'wysiwyg',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'show_in_graphql'   => 0,
									'default_value'     => '',
									'tabs'              => 'visual',
									'toolbar'           => 'basic',
									'media_upload'      => 0,
									'delay'             => 0,
									'parent_repeater'   => 'field_64526be579b76',
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_64526c1813e4b',
					'label'             => 'General Rules',
					'name'              => 'general_rules',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 0,
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_64526c1813e4c',
							'label'             => 'Banner',
							'name'              => 'banner',
							'aria-label'        => '',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'return_format'     => 'array',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
							'preview_size'      => 'medium',
						),
						array(
							'key'               => 'field_64526c1813e4d',
							'label'             => 'Headline',
							'name'              => 'headline',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_64526c1813e4f',
							'label'             => 'Rules',
							'name'              => 'rules',
							'aria-label'        => '',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'layout'            => 'table',
							'pagination'        => 0,
							'min'               => 0,
							'max'               => 0,
							'collapsed'         => '',
							'button_label'      => 'Add Rule',
							'rows_per_page'     => 20,
							'sub_fields'        => array(
								array(
									'key'               => 'field_64526c1813e50',
									'label'             => 'Rule',
									'name'              => 'rule',
									'aria-label'        => '',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'show_in_graphql'   => 0,
									'default_value'     => '',
									'maxlength'         => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'parent_repeater'   => 'field_64526c1813e4f',
								),
							),
						),
					),
				),
			),
			'location'                              => array(
				array(
					array(
						'param'    => 'page',
						'operator' => '==',
						'value'    => '129',
					),
				),
			),
			'menu_order'                            => 0,
			'position'                              => 'acf_after_title',
			'style'                                 => 'seamless',
			'label_placement'                       => 'top',
			'instruction_placement'                 => 'label',
			'hide_on_screen'                        => '',
			'active'                                => true,
			'description'                           => '',
			'show_in_rest'                          => 0,
			'show_in_graphql'                       => 0,
			'graphql_field_name'                    => 'pageFields—FestivalInformation',
			'map_graphql_types_from_location_rules' => 0,
			'graphql_types'                         => '',
		)
	);

	/** Page: History */
	acf_add_local_field_group(
		array(
			'key'                                   => 'group_643d94d6f2852',
			'title'                                 => 'Page Fields — History',
			'fields'                                => array(
				array(
					'key'               => 'field_643d94d765bba',
					'label'             => 'Gallery',
					'name'              => 'gallery',
					'aria-label'        => '',
					'type'              => 'gallery',
					'instructions'      => 'Select between 2 and 4 images',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'url',
					'library'           => 'all',
					'min'               => 2,
					'max'               => 4,
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'insert'            => 'append',
					'preview_size'      => 'large',
				),
				array(
					'key'               => 'field_643da0f79572b',
					'label'             => 'Capitol Grounds',
					'name'              => 'capitol',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_643da1199572c',
							'label'             => 'Image',
							'name'              => 'image',
							'aria-label'        => '',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
							'preview_size'      => 'large',
						),
						array(
							'key'               => 'field_643da1329572d',
							'label'             => 'Headline',
							'name'              => 'headline',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'Tuskahoma Capitol Grounds',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_643da1919572e',
							'label'             => 'Subheadline',
							'name'              => 'subheadline',
							'aria-label'        => '',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'rows'              => '',
							'placeholder'       => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.',
							'new_lines'         => '',
						),
					),
				),
				array(
					'key'               => 'field_643da1fe4f4e9',
					'label'             => 'History',
					'name'              => 'history',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_643da1fe4f4ea',
							'label'             => 'Image',
							'name'              => 'image',
							'aria-label'        => '',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
							'library'           => '',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
							'preview_size'      => 'large',
						),
						array(
							'key'               => 'field_643da1fe4f4eb',
							'label'             => 'Headline',
							'name'              => 'headline',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'Tuskahoma Capitol Grounds',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_643da1fe4f4ec',
							'label'             => 'Subheadline',
							'name'              => 'subheadline',
							'aria-label'        => '',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'rows'              => '',
							'placeholder'       => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.',
							'new_lines'         => '',
						),
					),
				),
				array(
					'key'               => 'field_643da1e64f4e5',
					'label'             => 'Traditions',
					'name'              => 'traditions',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_643da1e64f4e6',
							'label'             => 'Image',
							'name'              => 'image',
							'aria-label'        => '',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
							'preview_size'      => 'large',
						),
						array(
							'key'               => 'field_643da1e64f4e7',
							'label'             => 'Headline',
							'name'              => 'headline',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'Tuskahoma Capitol Grounds',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_643da1e64f4e8',
							'label'             => 'Subheadline',
							'name'              => 'subheadline',
							'aria-label'        => '',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'rows'              => '',
							'placeholder'       => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.',
							'new_lines'         => '',
						),
					),
				),
				array(
					'key'               => 'field_643da20eb67ee',
					'label'             => 'Video',
					'name'              => 'video',
					'aria-label'        => '',
					'type'              => 'oembed',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'width'             => '',
					'height'            => '',
				),
			),
			'location'                              => array(
				array(
					array(
						'param'    => 'page',
						'operator' => '==',
						'value'    => '10',
					),
				),
			),
			'menu_order'                            => 0,
			'position'                              => 'acf_after_title',
			'style'                                 => 'seamless',
			'label_placement'                       => 'top',
			'instruction_placement'                 => 'label',
			'hide_on_screen'                        => '',
			'active'                                => true,
			'description'                           => '',
			'show_in_rest'                          => 0,
			'show_in_graphql'                       => 0,
			'graphql_field_name'                    => 'history',
			'map_graphql_types_from_location_rules' => 0,
			'graphql_types'                         => '',
		)
	);

	/** Page: Home */
	acf_add_local_field_group(
		array(
			'key'                                   => 'group_6452749d05b78',
			'title'                                 => 'Page Fields — Home',
			'fields'                                => array(
				array(
					'key'               => 'field_6452749d81e4c',
					'label'             => 'Section 2',
					'name'              => 'section_2',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 0,
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_645274b581e4d',
							'label'             => 'About',
							'name'              => 'about',
							'aria-label'        => '',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'default_value'     => '',
							'maxlength'         => '',
							'rows'              => '',
							'placeholder'       => '',
							'new_lines'         => 'br',
						),
					),
				),
				array(
					'key'               => 'field_647a363846a32',
					'label'             => 'Map',
					'name'              => 'map',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 0,
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_647a364646a33',
							'label'             => 'Image',
							'name'              => 'image',
							'aria-label'        => '',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'return_format'     => 'array',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
							'preview_size'      => 'medium',
						),
						array(
							'key'               => 'field_647a366f46a34',
							'label'             => 'Subheadline',
							'name'              => 'subheadline',
							'aria-label'        => '',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'default_value'     => '',
							'maxlength'         => '',
							'rows'              => '',
							'placeholder'       => '',
							'new_lines'         => '',
						),
					),
				),
				array(
					'key'               => 'field_647a36a4520bf',
					'label'             => 'Facebook',
					'name'              => 'facebook',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 0,
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_647a36a4520c0',
							'label'             => 'Image',
							'name'              => 'image',
							'aria-label'        => '',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'return_format'     => 'array',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
							'preview_size'      => 'medium',
						),
						array(
							'key'               => 'field_647a36a4520c1',
							'label'             => 'Subheadline',
							'name'              => 'subheadline',
							'aria-label'        => '',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'default_value'     => '',
							'maxlength'         => '',
							'rows'              => '',
							'placeholder'       => '',
							'new_lines'         => '',
						),
					),
				),
			),
			'location'                              => array(
				array(
					array(
						'param'    => 'page',
						'operator' => '==',
						'value'    => '2',
					),
				),
			),
			'menu_order'                            => 0,
			'position'                              => 'acf_after_title',
			'style'                                 => 'seamless',
			'label_placement'                       => 'top',
			'instruction_placement'                 => 'label',
			'hide_on_screen'                        => '',
			'active'                                => true,
			'description'                           => '',
			'show_in_rest'                          => 0,
			'show_in_graphql'                       => 0,
			'graphql_field_name'                    => 'pageFields—Home',
			'map_graphql_types_from_location_rules' => 0,
			'graphql_types'                         => '',
		)
	);

	/** Page: Registration Form */
	acf_add_local_field_group(
		array(
			'key'                                   => 'group_643d63aa08146',
			'title'                                 => 'Page Fields — Registration Form',
			'fields'                                => array(
				array(
					'key'               => 'field_64837e784dc3b',
					'label'             => 'External Registration Link?',
					'name'              => 'has_external_registration_link',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 0,
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'field_64837e424dc3a',
					'label'             => 'Registration Form',
					'name'              => 'registration_form',
					'aria-label'        => '',
					'type'              => 'forms',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_64837e784dc3b',
								'operator' => '!=',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 0,
					'return_format'     => 'id',
					'allow_null'        => 1,
					'multiple'          => 0,
				),
				array(
					'key'               => 'field_64837e984dc3c',
					'label'             => 'External Registration Link',
					'name'              => 'external_registration_link',
					'aria-label'        => '',
					'type'              => 'url',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_64837e784dc3b',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_648a217348834',
					'label'             => 'Additional Information',
					'name'              => 'additional_information',
					'aria-label'        => '',
					'type'              => 'wysiwyg',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 0,
					'default_value'     => '',
					'tabs'              => 'all',
					'toolbar'           => 'basic',
					'media_upload'      => 0,
					'delay'             => 1,
				),
			),
			'location'                              => array(
				array(
					array(
						'param'    => 'post_template',
						'operator' => '==',
						'value'    => 'templates/page-template-registrations.php',
					),
				),
				array(
					array(
						'param'    => 'page',
						'operator' => '==',
						'value'    => '11',
					),
				),
			),
			'menu_order'                            => 0,
			'position'                              => 'acf_after_title',
			'style'                                 => 'normal',
			'label_placement'                       => 'top',
			'instruction_placement'                 => 'label',
			'hide_on_screen'                        => '',
			'active'                                => true,
			'description'                           => '',
			'show_in_rest'                          => 0,
			'show_in_graphql'                       => 0,
			'graphql_field_name'                    => 'registrationForm',
			'map_graphql_types_from_location_rules' => 0,
			'graphql_types'                         => '',
		)
	);

	/** Page: Staff */
	acf_add_local_field_group(
		array(
			'key'                                   => 'group_6452955626eae',
			'title'                                 => 'Page Fields — Staff',
			'fields'                                => array(
				array(
					'key'               => 'field_6452955697931',
					'label'             => 'Section 3',
					'name'              => 'section_3',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 0,
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6452957397932',
							'label'             => 'Image',
							'name'              => 'image',
							'aria-label'        => '',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'return_format'     => 'array',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
							'preview_size'      => 'medium',
						),
						array(
							'key'               => 'field_6452958297933',
							'label'             => 'Headline',
							'name'              => 'headline',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_6452958b97934',
							'label'             => 'Subheadline',
							'name'              => 'subheadline',
							'aria-label'        => '',
							'type'              => 'wysiwyg',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'default_value'     => '',
							'tabs'              => 'visual',
							'toolbar'           => 'basic',
							'media_upload'      => 0,
							'delay'             => 0,
						),
					),
				),
				array(
					'key'               => 'field_645295a7772ab',
					'label'             => 'Section 4',
					'name'              => 'section_4',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 0,
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_645295a7772ac',
							'label'             => 'Image',
							'name'              => 'image',
							'aria-label'        => '',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'return_format'     => 'array',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
							'preview_size'      => 'medium',
						),
						array(
							'key'               => 'field_645295a7772ad',
							'label'             => 'Headline',
							'name'              => 'headline',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						),
						array(
							'key'               => 'field_645295a7772ae',
							'label'             => 'Subheadline',
							'name'              => 'subheadline',
							'aria-label'        => '',
							'type'              => 'wysiwyg',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'default_value'     => '',
							'tabs'              => 'visual',
							'toolbar'           => 'basic',
							'media_upload'      => 0,
							'delay'             => 0,
						),
					),
				),
				array(
					'key'               => 'field_645295b2bac0c',
					'label'             => 'Training Videos',
					'name'              => 'training_videos',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 0,
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_645295cabac0d',
							'label'             => 'Videos',
							'name'              => 'videos',
							'aria-label'        => '',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 0,
							'layout'            => 'table',
							'pagination'        => 0,
							'min'               => 0,
							'max'               => 0,
							'collapsed'         => '',
							'button_label'      => 'Add Row',
							'rows_per_page'     => 20,
							'sub_fields'        => array(
								array(
									'key'               => 'field_645295dfbac0e',
									'label'             => 'Video URL',
									'name'              => 'video',
									'aria-label'        => '',
									'type'              => 'oembed',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'show_in_graphql'   => 0,
									'width'             => '',
									'height'            => '',
									'parent_repeater'   => 'field_645295cabac0d',
								),
							),
						),
					),
				),
			),
			'location'                              => array(
				array(
					array(
						'param'    => 'page',
						'operator' => '==',
						'value'    => '39',
					),
				),
			),
			'menu_order'                            => 0,
			'position'                              => 'acf_after_title',
			'style'                                 => 'seamless',
			'label_placement'                       => 'top',
			'instruction_placement'                 => 'label',
			'hide_on_screen'                        => '',
			'active'                                => true,
			'description'                           => '',
			'show_in_rest'                          => 0,
			'show_in_graphql'                       => 0,
			'graphql_field_name'                    => 'pageFields—Volunteers',
			'map_graphql_types_from_location_rules' => 0,
			'graphql_types'                         => '',
		)
	);

	/** Post Type: Entertainment & Events */
	acf_add_local_field_group(
		array(
			'key'                                   => 'group_64396c4b2757e',
			'title'                                 => 'Post Fields — Event Info',
			'fields'                                => array(
				array(
					'key'               => 'field_6476614134813',
					'label'             => 'Portrait Orientation Photo (Featured Image should be 16:9 orientation)',
					'name'              => 'portrait_orientation_photo',
					'aria-label'        => '',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'return_format'     => 'array',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'preview_size'      => 'medium',
				),
				array(
					'key'               => 'field_64396c4b4370a',
					'label'             => 'Description',
					'name'              => 'description',
					'aria-label'        => '',
					'type'              => 'wysiwyg',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'default_value'     => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.',
					'tabs'              => 'all',
					'toolbar'           => 'basic',
					'media_upload'      => 0,
					'delay'             => 0,
				),
				array(
					'key'               => 'field_64396c774370b',
					'label'             => 'Info',
					'name'              => 'info',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_64396c814370c',
							'label'             => 'Day',
							'name'              => 'day',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'Friday'   => 'Friday',
								'Saturday' => 'Saturday',
								'Sunday'   => 'Sunday',
							),
							'default_value'     => false,
							'return_format'     => 'value',
							'multiple'          => 0,
							'allow_null'        => 0,
							'ui'                => 0,
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_64396ca44370d',
							'label'             => 'Start Time',
							'name'              => 'start_time',
							'aria-label'        => '',
							'type'              => 'time_picker',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'display_format'    => 'g:i a',
							'return_format'     => 'g:i a',
						),
						array(
							'key'               => 'field_64396cea34b07',
							'label'             => 'End Time',
							'name'              => 'end_time',
							'aria-label'        => '',
							'type'              => 'time_picker',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'display_format'    => 'g:i a',
							'return_format'     => 'g:i a',
						),
					),
				),
			),
			'location'                              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'events',
					),
				),
			),
			'menu_order'                            => 0,
			'position'                              => 'acf_after_title',
			'style'                                 => 'default',
			'label_placement'                       => 'top',
			'instruction_placement'                 => 'label',
			'hide_on_screen'                        => '',
			'active'                                => true,
			'description'                           => '',
			'show_in_rest'                          => 1,
			'show_in_graphql'                       => 1,
			'graphql_field_name'                    => 'event_info',
			'map_graphql_types_from_location_rules' => 0,
			'graphql_types'                         => '',
		)
	);

endif;

if ( function_exists( 'acf_add_local_field_group' ) ) :

	/** Theme Settings: Footer */
	acf_add_local_field_group(
		array(
			'key'                                   => 'group_6447d3fe94778',
			'title'                                 => 'Theme Settings — Footer Settings',
			'fields'                                => array(
				array(
					'key'               => 'field_6447d43afb7b8',
					'label'             => 'Footer Image',
					'name'              => 'footer_image',
					'aria-label'        => '',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 0,
					'return_format'     => 'array',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'preview_size'      => 'large',
				),
				array(
					'key'               => 'field_6447d45cfb7b9',
					'label'             => 'Social Links',
					'name'              => 'socials',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 1,
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6447d471fb7ba',
							'label'             => 'Instagram',
							'name'              => 'instagram',
							'aria-label'        => '',
							'type'              => 'url',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 1,
							'default_value'     => '',
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_6447d480fb7bb',
							'label'             => 'Facebook',
							'name'              => 'facebook',
							'aria-label'        => '',
							'type'              => 'url',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'show_in_graphql'   => 1,
							'default_value'     => '',
							'placeholder'       => '',
						),
					),
				),
			),
			'location'                              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'acf-options-footer-settings',
					),
				),
			),
			'menu_order'                            => 0,
			'position'                              => 'normal',
			'style'                                 => 'default',
			'label_placement'                       => 'top',
			'instruction_placement'                 => 'label',
			'hide_on_screen'                        => '',
			'active'                                => true,
			'description'                           => '',
			'show_in_rest'                          => 0,
			'show_in_graphql'                       => 0,
			'graphql_field_name'                    => 'themeSettings',
			'map_graphql_types_from_location_rules' => 0,
			'graphql_types'                         => '',
		)
	);

	/** Theme Settings: General */
	acf_add_local_field_group(
		array(
			'key'                                   => 'group_64639245a1e82',
			'title'                                 => 'Theme Settings — General',
			'fields'                                => array(
				array(
					'key'               => 'field_6463924642596',
					'label'             => 'Enable Weather Alert?',
					'name'              => 'enable_weather_alert',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 0,
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'field_6463928165d1c',
					'label'             => 'Alert Text',
					'name'              => 'alert_text',
					'aria-label'        => '',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_6463924642596',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'show_in_graphql'   => 0,
					'default_value'     => '[Event] has been delayed until [time]',
					'maxlength'         => '',
					'rows'              => '',
					'placeholder'       => '',
					'new_lines'         => 'br',
				),
			),
			'location'                              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'theme-general-settings',
					),
				),
			),
			'menu_order'                            => 0,
			'position'                              => 'normal',
			'style'                                 => 'default',
			'label_placement'                       => 'top',
			'instruction_placement'                 => 'label',
			'hide_on_screen'                        => '',
			'active'                                => true,
			'description'                           => '',
			'show_in_rest'                          => 0,
			'show_in_graphql'                       => 0,
			'graphql_field_name'                    => 'themeSettings—WeatherAlert',
			'map_graphql_types_from_location_rules' => 0,
			'graphql_types'                         => '',
		)
	);

	/** Removes explicit "Operational Hours" Field Group in favor of GUI-defined Operational Hours */
	acf_remove_local_field_group( 'group_6447d4956d6aa' );
	acf_get_store( 'field-groups' )->remove( 'group_6447d4956d6aa' );

endif;