name: Deploy to WP Engine
on:
    push:
        branches: [dev, stg, main, v*]

jobs:
    deploy-prod:
        name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        uses: choctaw-nation/shared-github-actions/.github/workflows/deploy.yml@main
        with:
            WPE_ENV: labordayprod # WP Engine environment name
            theme_name: labor-day
        secrets: inherit

    deploy-stg:
        name: Deploy to Staging
        if: github.ref == 'refs/heads/stg'
        uses: choctaw-nation/shared-github-actions/.github/workflows/deploy.yml@main
        with:
            WPE_ENV: labordaystg # WP Engine environment name
            theme_name: labor-day
        secrets: inherit

    deploy-dev:
        name: Deploy to Development
        if: github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/heads/v')
        uses: choctaw-nation/shared-github-actions/.github/workflows/deploy.yml@main
        with:
            WPE_ENV: labordaydev # WP Engine environment name
            theme_name: labor-day
        secrets: inherit
